### PR TITLE
Space Traveler's Hub: Fetch and display missions

### LINKED ISSUE #15: [4pt] Display missions - Lists render
- Use `useSelector()` Redux Hook to select the state slices and render lists of  missions in corresponding routes. i.e.:
```javascript
// get rockets data from the store
const rockets = useSelector(state => state.rockets);
```

- You can style the whole application "by hand" or you could use [React Bootstrap](https://react-bootstrap.github.io/), a UI library that could speed up the process. This is a popular library and working with its components would be good practice.
- Render a table with the missions' data (as per design).

### LINKED ISSUE #18: [4pt]  Fetch missions - Fetch data
Fetch data from the Missions endpoint  (https://api.spacexdata.com/v3/missions) when a user navigates to the Missions section.

Once the data are fetched, dispatch an action to store the selected data in Redux store:

- mission_id
- mission_name
- description

NOTE: Make sure you only dispatch those actions once and do not add data to store on every re-render (i.e. when changing views / using navigation).

### LINKED ISSUE #20: [1pt] Create basic structure for Missions - Setup
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

### PR DESCRIPTION
**Pull request by Timbar09**
In this PR, I fetched and displayed missions data

**Changes**

- Add navbar
- Add routing system
- Created a basic structure of missions
- Installed React Redux toolkit
- Added Redux store.js
- Fetched missions data from the mission external API
- Displayed missions data on the UI

### CODE REVIEW

**Comment by Shakir-Hussain12** [comment]
**Invalid Request**
---
Hi @Timbar09, Good job, but I can't proceed to approve this PR, as the linters are failing. 
Kindly fix the issue and push the changes for me to review.

**Positives**
- Router Links work fine.
- Correct Fetch Calls.

**Changes Required**
- Stylelint errors

**Review by Shakir-Hussain12 — CHANGES_REQUESTED** [review]
**Invalid Request**
---
Hi @Timbar09, Good job, but I can't proceed to approve this PR, as the linters are failing. 
Kindly fix the issue and push the changes for me to review.

**Positives**
- Router Links work fine.
- Correct Fetch Calls.

**Changes Required**
- ESLint errors

**Comment by Timbar09** [comment]
@Shakir-Hussain12 the linter errors are showing on the GitHub site but not locally. 

I'll ensure the linters are current and come up with a solution.

**Comment by Timbar09** [comment]
@Shakir-Hussain12 I've made the changes and I think we are all clear. Check it out and tell me what you think.

**Review by Shakir-Hussain12 — APPROVED** [review]
Hi @Timbar09, Great work implementing the requested changes. 
You're good to merge the code now.

**Pull request merged**
